---
abstract: 'Share your Carp::Clan settings with your whole Clan'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Clan-Share
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp::Clan: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/Carp-Clan-Share/tree/master
version: 0.013
